version: '3.9'
services:
  auth-api:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      JWT_SECRET: change-me
      DB_PATH: /data/app.db
      DB_BACKUP_DIR: /data/backups
      DB_BACKUP_INTERVAL_MINUTES: 60
    volumes:
      - .:/app
      - ./data:/data
