name: Backend CI

on:
  pull_request:
    paths:
      - 'Server/**'
      - '.github/workflows/backend-ci.yml'
  push:
    branches:
      - main
    paths:
      - 'Server/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test-and-lint:
    name: Install, lint, and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Server
    env:
      DATABASE_URL: ${{ secrets.BACKEND_DATABASE_URL }}
      JWT_SECRET: ${{ secrets.BACKEND_JWT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        env:
          NODE_ENV: test
        run: npm test
